print("Cntent-Type: text/palin\r")
print("\r")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")
print("hello world!")